name: Build Maven Package And Publish Docker Image

on:
  push:
    branches:
      - master
      - setup_actions

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Extract Project Version
        run: echo "version=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT
        id: project

      - name: Show Project version
        run: echo ${{steps.project.outputs.version}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: tranhungkt/service:latest


  deploy:
    needs: build
    runs-on: engage-service-aws
    steps:
      - name: Pull image from docker hub
        run: docker pull tranhungkt/service:latest
      - name: Delete old container
        run: docker rm -f engage-together-service-container
      - name: Run docker container
        run: docker run -d --name engage-together-service-container tranhungkt/service